const arKeys = {
  'complaints': 'الشكاوي',
  'message': 'الرسالة',
  'enter_complaint_title': 'ادخل العنوان',
  'required': 'مطلوب',
  "contact_us_on_telegram": "تواصل معنا على تيليجرام",
  "contact_us_on_whatsapp": "تواصل معنا على الواتس",
  "are_you_want_to_delete_bill": "هل تريد مسح الفاتورة",
  "no_chat_write_your_first_message":
      "لا يوجد رسائل قديمة يمكنك بداء المحادثة الان",
  "driver_bank_bills": "فواتيري البنكية",
  "bank_bills": "فواتير بنكية",
  "no_bank_bills": "لا يوجد فواتير بنكية",
  "not_valid_coupon": "الكوبون غير صالح",
  "not_found_coupon": "الكوبون غير صالح",
  "you_have_discount": "لديك خصم بقيمه",
  "coupon_is_not_valid": "كوبون منتهي الصلاحية",
  "minim_price": "الحد الادني",
  "zero_results": "لا يوجد نتائج",
  "not_valid_price": "السعر غير صالح",
  "products_names_must_not_be_empty": "لا تترك اسم المنتج فارغ",
  "tam": "تم",
  "must_login_desc": "يجب تسجيل الدخول اولا للوصول لهذه الصفحة",
  "offer_created_sucessfuly": "تم ارسال العرض بنجاح",
  "drop_place": "موقع التسليم",
  "pick_place": "موقع الاستلام",
  "call_driver": "اتصل بالسائق",
  "find_driver_location": "مكان السائق",
  "deptit_amount": "المديونية",
  "you_have_to_pay": "يجب سداد",
  "pick compliant image": "اختيار صورة الشكوي",
  "reviews": "التقيم",
  "products": "الطلبات",
  "order_is_done": "تم انهاء الطلب",
  "finish_order": "انهاء الطلب",
  "app_title": "قدها",
  "must_login_first": "يجب تسجيل الدخول اولا",
  "not_valid_form": "تاكد من البيانات",
  "pick_bill_image": "اختيار صورة الفاتورة",
  "note": "ملحوظة",
  "create_new_complaint": "تسجيل شكوي جديدة",
  "enter_bill_amount": "ادخل قيمة الفاتورة",
  "must_enter_bill_image": "يجب ادخال صورة الفاتورة",
  "no_order_Bills": "لا يوجد فواتير",
  "bills": "الفواتير",
  "update_account_data": "تحديث بيانات الحساب",
  "welcome": "اهلا بك يا ",
  "greeatings_chat_message": "مرحبا بك في شاشة المساعده",
  "how_can_i_serve_you": "ازاي اقدر اساعدك ؟",
  "new_order": "طلب جديد",
  "quick_order": "توصيل طرود",
  "comlaints": "الشكاوي",
  "drop_to_home": "المنزل",
  "other_place": "مكان اخر",
  "price": "السعر",
  "confrim_offer_dialog": "تاكيد القبول علي العرض",
  "meter": "متر",
  "confirm": "تاكيد",
  "empty": "لا يوجد",
  "rate_order": "تقيم الاوردر",
  "no_complains": "لا يوجد شكاوي",
  "right_pin_code": "كود دخول صحيح",
  "this_lang_name": "عربي",
  "location_perrmison_denied": "",
  "must_enable_from_settings": "",
  "must_open_location_services": "",
  "phone_number_is_too_long": "رقم الهاتف طويل جدا",
  "phone_number_is_too_short": "رقم الهاتف قصير جدا",
  "car_image_is_missing_2": "يجب اختيار صورتين للسيارة",
  "car_image_is_missing": "صور السيارة مطلوبة",
  "form_image_is_missing": "صورة الاستمارة مطلوبة",
  "license_image_is_missing": "صورة الرخصه مطلوبة",
  "id_image_is_missing": "صورة الهويه مطلوبة",
  "validaton_faliure": "تاكد من جميع الخانات",
  "too_short": "قصير جدا",
  "enter_personal_id": "يجب ادخال رقم الهويه الوطنية",
  "enter_your_stc_no": "يجب ادخال رقم stc",
  "enter_your_phone_no": "يجب ادخال رقم الهاتف",
  "enter_your_email": "يجب ادخال البريد الالكتورني",
  "name_is_too_short": "الاسم قصير",
  "enter_your_name": "يجب ادخال الاسم",
  "back": "رجوع",
  "not_valid_ksa_phone_number": "يجب ادخال رقم سعودي صحيح",
  "phone": "رقم الهاتف",
  "unkwon_error": "حدث خطا ما",
  "must_pick_profile_picture": "يجب اختيار صورة للمف الشخصي",
  "edit_acount_data": "تعديل بيانات الحساب",
  "blocked_account": "الحساب محظور",
  "plase_update_your_data": "من فضلك حدث بياناتك",
  "refuesd_account": "الحساب مرفوض",
  "pending_account": "الحساب قيد المراجعة",
  "plase_wait_untill_we_review_your_account":
      "يرجي الانتظار حتي يتم مراجعه بياناتك",
  "code_has_been_sent_to_your_phone": "تم ارسال الكود الي هاتفك",
  "must_sign_up_first": "يجب انشاء حساب",
  "sign_up_as_driver": "انشاء حساب سائق",
  "sign_up_as_client": "انشاء حساب عميل",
  "hello_world": "اهلاً بالعالم",
  "gadha": "قدها",
  "app_name": "قدها",
  "we_will_send_you_code": "سنرسل لك رمز التفعيل لتوثيق الحساب",
  "phone_number": "رقم الهاتف",
  "please_re_enter_number": "من فضلك ادخل الرقم صحيح",
  "login": "دخول",
  "skip": "تخطي",
  "register_as_agent": " سجل كمندوب",
  "terms_of_servis":
      "من خلال الضغط علي التالي أوكد أني قرأت و وافقت علي شروط و احكام خدمة قدها بالإضافة الي سياسة الخصوصية",
  "we_will_send_you_code_to_number": "سنرسل لك رمز التفعيل علي الرقم",
  "edit_number": "تعديل الرقم ؟",
  "enter_4_numbers_code": "ادخل الكود الذي يتكون من 4 ارقام",
  "resend_code": "إعادة ارسال الرمز",
  "activate": "تفعيل",
  "error_pin_field_can't_be_empty": "ادخل الكود كاملاً",
  "sign_in": "تسجيل الدخول",
  "personal_pic": "صورتك الشخصية",
  "mustn't_5 mega": "يجب ان لا تتخطي ال 5 ميغا ",
  "image_source": "مصدر الصورة",
  "image_source_des": "من فضلك اختار مصدر الصورة التي تود ان ترفع",
  "from_gallery": "اختار من المعرض",
  "from_camera": "اختار من الكاميرا",
  "stc_number": "رقم STC pay",
  "e-mail": "البريد الالكتروني",
  "please_re_enter_e-mail": "من فضلك ادخل البريد الاكتروني بشكل صحيح",
  "male": "ذكر",
  "female": "انثى",
  "gender": "النوع",
  "sign_in_b": "تسجيل",
  "settings": "الاعدادات",
  "visitor": "زائر",
  "needs_setup": "يحتاج للاضافة",
  "edit": "تعديل",
  "send_notification": "ارسال الاشعارات",
  "change_mobile_number": "تغير رقم الجوال",
  "usage_policy": "سياسة الاستخدام",
  "complains_list": "قائمة الشكاوي",
  "app_lang": "لغة التطبيق",
  "arabic": "العربية",
  "english": "الانجليزية",
  "choose_device_lang": "اختار لغة التطبيق",
  "info": "معلومة",
  "restart_to_apply_lang":
      "من المًقترح ان تعيد تشغل التطبيق لكي يتم تطبيق تغير اللغة بالكامل",
  "api_key_error": "هذه الميزة ليست مًفعلة\n من فضلك تواصل مع المطور",
  "account_balance": "رصيد الحساب",
  "orders_number": "عدد الطلبات",
  "services_ratings": "تقيمات الخدمات",
  "coupon": "الكوبون",
  "payment": "طريقة السداد",
  "contact_us": "اتصل بنا",
  "sign_out": "تسجيل الخروج",
  "rs": "ريال",
  "orders": "طلبات",
  "add_coupon": "اضافة كوبون",
  "add_coupon_b": "اضف كوبون",
  "enter_code": "ادخل الرمز",
  "follow_us_for_more": "للمزيد من الكوبونات تابعنا ع مواقعنا",
  "check": "تحقق",
  "cach": "كاش",
  "add_credit_card": "اضف بطاقة بنكية",
  "prev": "السابق",
  "next": "التالي",
  "done": "انهاء",
  "card_number": "رقم البطاقة",
  "cardHolder_name": "اسم صاحب البطاقة",
  "valid_thru": "معاد الانهاء",
  "SECURITY_CODE_CVC": "كود الامان (CVC)",
  "NAME_SURNAME": "الاسم",
  "no_services_ratings": "لا يوجد تقييمات",
  "update": "تحديث",
  "name": "الاسم",
  "address": "العنوان",
  "store_address": "عنوان المتجر",
  "client_address": "عنوان العميل",
  "re_enter_your_name": "اعد كتابة اسمك بشكل صحيح",
  "your_details": "بياناتي",
  "sign_in_as_agent": "تسجيل الدخول كمندوب",
  "vehicle": "معلومات المركبة",
  "vehicle_number": "رقم المركبة",
  "form_photo": "صورة الاستمارة",
  "form_should_be_valid": "يجب ان تكون الاستمارة سارية المفعول",
  "personal_driving_license_pic": "صورة رخصة القيادة",
  "form_should_be_valid_license": "يجب ان تكون الرخصة  سارية المفعول",
  "personal_id_pic": "صورة بطاقة التعريف الشخصي",
  "personal_id_num": "رقم بطاقة التعريف الشخصي",
  "form_should_be_valid_id": "يجب ان تكون سارية المفعول",
  "vehicle_photoes": "صور المركبة",
  "front_rear_vehicle_pics": "صورة امامية و خلفية للمركبة",
  "ok": "حسناً",
  "cancel": "اغلاق",
  "please_enter_your_data":
      "تأكد من ادخال جميع بيانياتك وخصوصاً صورة شخصية, صورتان للمركبة, صورة سارية لرخصة القيادة وصورة الاستمراة",
  "data_isn't_enough": "معلومات ناقصة",
  "multi_image-picking_desc":
      "من فضلك اختار الصور الاعلي جودة دائماً لضمان وضوح المحتوي",
  "my_current_location": "مكاني الحالي",
  "search": "بحث...",
  "near_by_shops": "المتاجر الاقرب لك",
  "our_services": "خدماتنا",
  "enter_search_word": "ادخل كلمة للبحث عنها",
  "enjoy_discount": "تمتع بالخصم",
  "restaurants": "المطاعم",
  "details": "التفاصيل",
  "shares": "المشاركات",
  "menu": "المنيو",
  "hour": "ساعة",
  "open": "مفتوح",
  "closed": "مُغلق",
  "close": "اغلاف",
  "write_your_order": "اكتب طلبك",
  "write_your_orders": "اكتب طلبك",
  "instructions_for_the_delievery": "تعليمات للمرسول",
  "write_your_instrutions": "اكتب طلبك...",
  "add_discount_coupon": "اضف كوبون خصم",
  "discount_coupon": "كوبون خصم",
  "complete_your_order": "اكمل طلبك",
  "from": "من",
  "to": "الي",
  "the_order": "الطلب",
  "shipping_cost": "تكلفة التوصيل",
  "searching_for_agent": "جار البحث عن سائق",
  "enter_your_coupon": "ادخل الكوبون",
  "enter": "ادخال",
  "order_details": "تفاصيل الطلب",
  "the_agent": "السائق",
  "call_agent": "اتصل بالسائق",
  "locat_order_location": "تتبع الطلب",
  "problem_report": "ابلاغ عن مشكلة",
  "delete_all": "حذف الكل",
  "accept": "قبول",
  "decline": "رفض",
  "on_going_orders": "الطلبات الجديدة",
  "orders_menu": "قائمة الطلبات",
  "active": "متصل",
  "the_cost": "التكلفة",
  "app_commission": "عمولة التطبيق",
  "total": "الاجمالي",
  "follow_safty_instructions": "برجاء اتباع علامات السلامة في طلبك",
  "be_sure_of_the_client": "تأكد من جدية العميل",
  "drive_slowly_and_safely": "سر بشكل بطيء و أمن",
  "ware_your_gloves_mask": "ارتدي  كمامتك و قفازك",
  "revieve_your_money_first": "استلم مالك اولا",
  "start_your_trip": "ابداء رحلتك",
  "contact_client": "تواصل مع العميل",
  "the_place": "المكان",
  "call_client": "اتصل بالعميل",
  "delivery_completed": "تم التوصيل",
  "issue_the_bill": "اصدار فاتورة",
  "please_enter_bill_value": "برجاء ادخال قيمة الفاتورة المصدرة",
  "total_order_price": "تكلفة الطلبات",
  "bill_image": "صورة الفاتورة",
  "bill_should_incloud_all": "يجب ان تكون بكل الطلبات المرفقه بالطلب",
  "add_another_bill": "إضافة فاتورة اخري",
  "issue_bill": "اصدر الفاتورة",
  "your_rating": "تعليقك",
  "write_your_comment": "...اكتب تعليقاً ",
  "what_is_your_experience_with_client": "كيف كانت تجربتك مع العميل",
  "what_is_your_experience_with_driver": "كيف كانت تجربتك مع السائق",
  "leave_a_comment": "اترك تعليقك",
  "rate": "تقييم",
  "notifications": "الاشعارات",
  "your_orders": "طلباتك",
  "refresh": "تحديث",
  "copy": "نسخ",
  "retry": "اعادة المحاولة",
  "no_notifications": "لا يوجد اشعارات جديدة",
  "error": "حدث خطأ ما",
  "loading": "تحميل...",
  "no_reviews": "لا يوجد مشاركات",
  "be_first_reviewer": "كُن اول من يراجع",
  "phone_number_isn't_available": "رقم الهاتف غير متوفر",
  "no_orders": "لا يوجد لديك طلبات",
  "refresh_data": "تحديث",
  "write_your_product_name": "اكتب اسم المُنتج",
  "add_product": "اضافة مُنتج",
  "distenation": "وجهة التسليم",
  "continue": "استمرار",
  "unkown": "غير مُحدد",
  "error_happened": "حدث خطأ ما, حاول لاحقاً",
  "submit_order": "تنفيذ الطلب",
  "are_you_sure": "تنفيز الطلب",
  "submit_an_order":
      "عند تنفيز الطلب سوف يتم تحويل سيادتكم الى اقرب سائق مُتاح لتوصيل طلبكم",
  "start_searching_now": "ابدأ بالحبث الان",
  "please_choose_the_products": "من فضلك ادخل المُنتجات المُراد توصيلها",
  "no_products": "لم يتم ادخال اي مُنتجات",
  "signing_out": "هل انت متأكد من تسجيل الخروج من التطبيق؟",
  "sign_out_b": "تسجيل الخروج",
  "order_note": "ملحوظة العميل",
  "enter_valid_copoun": "هذا الكوبون غير صحيح",
  "order_submitted": "تم الطلب بنجاح",
  "order_submitted_desc1":
      "تم ارسال اشعار لجميع السائقين, ويمكنكم متابعة عروض السائقين من صفحة الطلبات بالتطبيق",
  "back_to_home_screen": "عودة الى الصفحة الرئيسية",
  "filter": "فيلتر البحث",
  "search_distance": "مسافة البحث",
  "apply_filter": "اعرض",
  "products_toBuy": "المُنتجات المطلوبة",
  "delivery_address": "عنوان التوصيل",
  "pick_your_location": "حدد موقعك",
  "satelite": "قمر صناعي",
  "hyprid": "هجين",
  "normal": "خريطة",
  "same_as_phone_number": "نفس رقم الهاتف المُدخل سابقاً؟",
  "tap_to_name_product": "انقر لادخال اسم المُنتج",
  "show": "عرض",
  "bet": "اكتب عرضك",
  "write_your_bet": "اكتب عرضك لتوصيل الطلب",
  "enter_delivery_cost": "سعر التوصيل",
  "enter_delivery_time": "وقت التوصيل",
  "enter_bet": "قدم عرضك",
  "order_betted": "تم تقديم عرضك بنجاح, انتظر حتي يراجع العميل عرضك",
  "order_already_betted": "لقد قدمت عرضك بالفعل",
  "driver_bets_on_order": "عروض السائقين",
  "choose_bet": "اختار ذلك العرض من",
  "conferm_driver":
      "عند اختيارك لعرض السائق, سوف يقوم السائق بالتواصل معك وتوصيل طلبك فى المعاد المُحدد",
  "choose_this_driver": "اختار هذا العرض",
  "will_deliver_your_order": "يمكنني توصيل طلبكم بـ",
  "show_offers": "مشاهدة العروض المقدمة",
  "now_offers_yet": "لا يوجد عروض مُقدمة بعد",
  "order_assigned": "تم تعين الطلب للسائق",
  "choose_driver": "اختر مندوب للتوصيل",
  "new_order_message": "رسالة جديدة حول الطلب",
  "rate_driver": "قيم السائق",
  "chat_with_client": "تحدث مع العميل",
  "rate_client": "قيم العميل",
  "update_order_status": "حدث حالة الطلب",
  "enter_total_cost": "برجاء ادخال القيمة الكلية للطلب",
  "total_cost": "التكلفة الكلية",
  "update_order": "تحديث الطلب",
  "order_status_update_completed": "تم تحديث بيانات الطلب",
  "the_map": "الخريطة",
  "current_orders": "الطلبات الجارية",
  "total_products_cost": "التكلفة الكلية للمنتجات",
  "no_image_picking_permission":
      "لم يعط التطبيق تصريح بفتح الصور الخاصة بكم, اذهب الى الاعدادات لاعطاء التطبيق التصريح المناسب.",
  "order_delivery_status": "حالة التوصيل",
  "connecting": "جار التوصيل",
  "delivery_done": "تم التوصيل",
  "choose_status": "اختر الحالة",
  "no_permission": "لا يوجد تصريح",
  "from_driver": "بواسطة",
  "copyed_to_clipboard": "تم النسخ للحافظة",
  "problem_terms": "البنود",
  "problem_notes": "ملاحطة",
  "write_your_problem": "اكتب المشاكل التي واجهتها...",
  "problem_images": "صور للمشكلة",
  "add_problem_images": "اضف صور للمشكلة",
  "see_driver_reviews": "نبذة عن السائق",
  "you_can_cancel_after": "يمكنك الغاء الطلب خلال",
  "do_you_want_to_cancel": "هل تود الغاء الطلب؟",
  "you_have_to_reorder":
      "اذا قمت بالغاء الطلب, حينها يجب اعادة الطلب مرة اخر, هذا لان الحذف دائم",
  "cancel_now": "الغاء الطلب لان",
  "order_was_cancelled": "تم الغاء الطلب بنجاح",
  "enter_this_field": "من فضلك ادخل تلك البيانات",
  "title": "العنوان",
  "enter_title": "اكتب عنوان الشكوي...",
  "send": "ارسال",
  "complain_was_successful": "تم ارسال الشكوي بنجاح",
  "driver_can_not_take_order_again":
      "اذا قمت بالغاء الطلب فلن تتمكن من تقديم عرض على نفس الطلب مرة اخر",
  "image": "ارفق صورة",
  "voice_note": "ارفق رسالة صوتية",
  "drivers_reviews": "ملاحظات السائقين",
  "clients_reviews": "ملاحظات المستخدمين",
  "total_order_delivery_fees": "اجمالى رسوم التوصيل",
  "you_have": "لديك",
  "in_your_account_balance": "فى رصيد الحساب الخاص بك",
  "upload_bank_validation": "رفع صورة للتأكيد البنكي",
  "banck_validation_success": "تم رفع صورة التأكيد",
  "upload": "رفع صورة التأكيد",
  "pick_another_image": "اختار واحدة اخري",
  "you_should_upload_validation":
      "يجب عليك ان ترفع صورة لتأكيد حسابك البنكي لكي نتمكن من تفعيل خدمة الطلبات واستكمال عملك.",
  "enter_between": "ادخل سعر التوصيل بين",
  "and": "و",
  "after_removing_comission": "الباقي بعد خصم عمولة التطبيق",
  "change_order_status_first":
      "غير حالة الطلب اولاً لكي تتمكن من استخراج وارسال فاتورة",
  "km": "كم",
  "m": "م",
  "you": "انت",
  "pick_up_location": "موقع الاستلام",
  "delivery_location": "موقع التسليم",
  "custom_request": "ارسله عني",
  "choose_loction": "اختر الموقع",
  "drop_location": "التوصيل الى",
  "choose_drop_location": "اختر مكان التسليم",
  "pickup_point": "نقطة الاستلام",
  "choose_pickup_point": "اختر نقطة الاستلام",
  "custom_package_order": "طرد خاص",
  "orders_to_accept": "طلبات جديده",
  "orders_in_progress": "طلبات جاريه",
  "orders_done": "طلبات منتهيه",
  "pick_location": "موقع الاستلام",
  "must_pick_image": "يجب اختيار صورة",
  "send_arrived_notification": "ارسال اشعار بوصولك",
  "order_taken": "تم استلام الطلب",
  "take_order": "تاكيد استلام الطلب",
  "notifications_send_sucessfuly": "تم ارسال الاشعار بنجاح",
  "send_noti_you_arrived": "ارسال اشعار بوصولك",
  "must_pick_pick_location": "يجب اختيار عنوان الطلب",
  "must_pick_drop_location": "يجب ادخال عنوان التسليم",
  "must_enter_product_name": "يجب ادخال اسم الطلب",
  "order_created_sucessfully": "تم عمل الاوردر بنجاح",
  "must_pick_location": "يجب اختيار عنوان",
  "plase_wait": "يرجي الانتظار",
  "must_enter_order_items": "يجب كتابة الطلبات",
  "products_to_buy": "الطلبات",
  "far_from": "يبعد",
  "no_offers": "لا يوجد عروض",
  "order": "طلباتي",
  "my_offers": "عروضي",
  "min_price": "اقل سعر",
  "max_price": "اقصي سعر",
  "my_reviews": "تقييمي",
  "gadhaapp_name": "قدها",
  'write_yor_orders': 'التقييمات',
};
