const enKeys = {
  'complaints': 'complaints',
  'enter_complaint_title': 'enter complaint title',
  'required': 'required',
  "empty": "empty ",
  "bank_bills": "bank bills",
  "no_bank_bills": "no bank bills",
  "not_valid_coupon": "not valid coupon",
  "not_found_coupon": "not found coupon",
  "coupon_is_not_valid": "coupon is not valid",
  "not_valid_price": "not valid price",
  "pick compliant image": "pick compliant image",
  "other_place": "other place",
  "contact_us_on_telegram": "contact us on telegream",
  "contact_us_on_whatsapp": "contact us on whatsapp",
  "no_chat_write_your_first_message": "no chat write your first message now",
  "minim_price": "minium price",
  "driver_bank_bills": "driver bank bills",
  "are_you_want_to_delete_bill": "Are you want to delete bill",
  "products_names_must_not_be_empty": "products names must not be empty",
  "tam": "done",
  "offer_created_sucessfuly": "offer created sucessfuly",
  "drop_place": "drop location",
  "pick_place": "pick locatin",
  "call_driver": "call the driver",
  "find_driver_location": "find driver location",
  "deptit_amount": "depit amount",
  "you_have_to_pay": "you have to pay",
  "reviews": "rates",
  "products": "order items",
  "must_login_desc": "you have to sign in to acess this page",
  "order_is_done": "order is done",
  "finish_order": "finish order",
  "app_title": "app title",
  "must_login_first": "must login first",
  "not_valid_form": "not valid form",
  "pick_bill_image": "pick bill image",
  "note": "note",
  "create_new_complaint": "create new complaint",
  "enter_bill_amount": "enter bill amount",
  "must_enter_bill_image": "must enter bill image",
  "no_order_Bills": "no order Bills",
  "bills": "bills",
  "update_account_data": "update account data",
  "welcome": "welcome",
  "greeatings_chat_message": "wellcome at help center !",
  "how_can_i_serve_you": "how can we help you ?",
  "new_order": "new order",
  "quick_order": "custom order",
  "comlaints": "comlaints",
  "drop_to_home": "home",
  "drop_to_other_place": "another place",
  "price": "price",
  "copy": "copy",
  "confrim_offer_dialog": "confrim offer",
  "meter": "meter",
  "close": "close",
  "confirm": "confirm",
  "rate_order": "Rate order",
  "no_complains": "no complains",
  "right_pin_code": "Right pin code",
  "must_pick_image": "must pick profile image",
  "plase_update_your_data": "plase update your data",
  "edit_acount_data": "Edit account data",
  "refuesd_account": "Refuesd account",
  "pending_account": "Pending account",
  "blocked_account": "blocked account",
  "plase_wait_untill_we_review_your_account":
      "plase wait untill we review your account",
  "send_arrived_notification": "send arrived notification",
  "pick_location": "Pick Location",
  "sign_up_as_client": "Sign Up As Client",
  "sign_up_as_driver": "Sign Up As Driver",
  "order_taken": "order taken",
  "take_order": "take order",
  "notifications_send_sucessfuly": "notifications send sucessfuly",
  "send_noti_you_arrived": "Send Noti You Arrived",
  "must_pick_pick_location": "must pick pick location",
  "must_pick_drop_location": "must pick drop location",
  "must_enter_product_name": "must enter product name",
  "order_created_sucessfully": "order created sucessfully",
  "must_pick_location": "must pick location",
  "plase_wait": "plase wait",
  "must_enter_order_items": "must enter order items",
  "products_to_buy": "Order To Buy",
  "far_from": "away",
  "no_offers": "No Offers Yet",
  "order": "Oreder",
  "my_offers": "My Offers",
  "min_price": "minimum price",
  "max_price": "maximum price",
  "my_reviews": "My Reviews",
  "orders_done": "Done",
  "orders_in_progress": "In Progress",
  "orders_to_accept": "to offer",
  "this_lang_name": "english",
  "hello_world": "Hello world",
  "gadha": "Gadha",
  "gadhaapp_name": "Gadha",
  "we_will_send_you_code":
      "We will send you an activation code to verify the account",
  "phone_number": "Phone Number",
  "please_re_enter_number": "Please entre a valid number",
  "login": "Log-in",
  "skip": "Skip",
  "register_as_agent": "Register as a driver",
  "terms_of_servis":
      "By clicking on Next, I confirm that I have read and agree to the terms and conditions of the Gadha service, in addition to the privacy policy",
  "we_will_send_you_code_to_number":
      "We will send you an activation code to the number",
  "edit_number": "Edit Number?",
  "enter_4_numbers_code": "Enter the code the 4-number code",
  "resend_code": "Resend code ",
  "activate": "Verify",
  "error_pin_field_can't_be_empty": "Enter the full code",
  "sign_in": "Login",
  "personal_pic": "Personal Image",
  "mustn't_5 mega": "Shouldn't be more than 5mb",
  "image_source": "Image Source",
  "image_source_des":
      "Please choose the source of the image you want to upload ",
  "from_gallery": "Choose from gallary",
  "from_camera": "Choose from camera",
  "stc_number": "STC pay number",
  "e-mail": "E-mail",
  "please_re_enter_e-mail": "Please enter your E-mail correctly",
  "male": "Male",
  "female": "Female",
  "gender": "Gender",
  "sign_in_b": "Register",
  "settings": "Settings",
  "visitor": "Visitor",
  "needs_setup": "It needs to be added",
  "edit": "Edit",
  "send_notification": "Send Notification",
  "change_mobile_number": "Change phone number",
  "usage_policy": "Usage Policy",
  "complains_list": "Complains List",
  "app_lang": "App language",
  "arabic": "Arabic",
  "english": "English",
  "choose_device_lang": "Choose app language",
  "info": "Information",
  "api_key_error":
      "Please contact with the developer\n This feature is disabled",
  "restart_to_apply_lang": "Restart the app to change the language",
  "account_balance": "Account Balance",
  "orders_number": "Orders Number",
  "services_ratings": "Services Rating",
  "coupon": "Coupon",
  "payment": "Payment Method",
  "contact_us": "Contact Us",
  "sign_out": "Sign out",
  "rs": "R.S",
  "orders": "orders",
  "add_coupon": "Add Coupon",
  "add_coupon_b": "Add Coupon",
  "enter_code": "Enter Code",
  "follow_us_for_more": "For more coupons, follow us on our websites",
  "check": "Verify",
  "cach": "Cash",
  "add_credit_card": "Add credit card",
  "prev": "Prev",
  "next": "Next",
  "done": "Finish",
  "card_number": "Card Number",
  "cardHolder_name": "Card holder name",
  "valid_thru": "Valid Data",
  "SECURITY_CODE_CVC": "Security Code (CVC)",
  "NAME_SURNAME": "Name",
  "no_services_ratings": "No Ratings",
  "update": "Update",
  "name": "Name",
  "address": "Address",
  "store_address": "Store Adress",
  "client_address": "Client Address",
  "re_enter_your_name": "Re-enter your name correctly",
  "your_details": "My Details",
  "sign_in_as_agent": "Sign in as a driver",
  "vehicle": "Vehicle Details",
  "vehicle_number": "Vehicle Number",
  "form_photo": "Form Image",
  "form_should_be_valid": "The form must be valid",
  "personal_driving_license_pic": "Driver's license image",
  "form_should_be_valid_license": "The license has to be valid",
  "personal_id_pic": "ID image",
  "personal_id_num": "ID number",
  "form_should_be_valid_id": "Should be valid",
  "vehicle_photoes": "Vehicle Image",
  "front_rear_vehicle_pics": "Front and back image of the vehicle",
  "ok": "Ok",
  "please_enter_your_data":
      "Make sure to enter all your details, especially a personal photo, two pictures of the vehicle, a valid copy of the driver's license and a copy of the form",
  "data_isn't_enough": "Incomplete Information",
  "cancel": "Cancel",
  "multi_image-picking_desc": "Please always choose the highest image quality",
  "my_current_location": "My current location",
  "search": "Search...",
  "near_by_shops": "Near-by Stores",
  "our_services": "Our Services",
  "enter_search_word": "Enter a Search Word",
  "enjoy_discount": "Enjoy Discount",
  "restaurants": "Resturants",
  "details": "Details",
  "shares": "Reviews",
  "menu": "Menu",
  "hour": "Hour",
  "open": "Open",
  "closed": "Closed",
  "write_your_order": "Order Now",
  "write_your_orders": "Order Now",
  "instructions_for_the_delievery": "Delivery Instructions",
  "write_your_instrutions": "Write your instructions...",
  "add_discount_coupon": "Add discount coupon",
  "discount_coupon": "Discount Coupon",
  "complete_your_order": "Continue",
  "from": "From",
  "to": "To",
  "the_order": "Order",
  "shipping_cost": "Delivery Cost",
  "searching_for_agent": "Searching for driver",
  "enter_your_coupon": "Enter coupon",
  "enter": "Enter",
  "order_details": "Order Details",
  "the_agent": "Driver",
  "call_agent": "Call Driver",
  "locat_order_location": "Locat your order",
  "problem_report": "Report a prblem",
  "delete_all": "Delete All",
  "accept": "Accept",
  "decline": "Dcline",
  "on_going_orders": "New Orders",
  "orders_menu": "Orders List",
  "active": "Active",
  "the_cost": "Cost",
  "app_commission": "Applications Commission",
  "total": "Total",
  "follow_safty_instructions": "Please follow the safty instructions",
  "be_sure_of_the_client": "Make sure the customer is serious",
  "drive_slowly_and_safely": "Drive slowly and safty",
  "ware_your_gloves_mask": "Put on your mask and gloves",
  "revieve_your_money_first": "Receive your money first",
  "start_your_trip": "Start your trip",
  "contact_client": "Chat with client",
  "the_place": "Location",
  "call_client": "Call Client",
  "issue_the_bill": "Issue the bill",
  "delivery_completed": "Delivery Completed",
  "please_enter_bill_value": "Please enter the bill total value",
  "total_order_price": "Orders cost",
  "bill_image": "Bill Image",
  "bill_should_incloud_all": "Bill should include all order products",
  "add_another_bill": "Add another bill",
  "issue_bill": "Issue the Bill",
  "your_rating": "Review",
  "write_your_comment": "Write a comment... ",
  "what_is_your_experience_with_client":
      "How was your experience with the client?",
  "what_is_your_experience_with_driver":
      "How was your experience with the driver?",
  "leave_a_comment": "Comment",
  "rate": "Rate",
  "notifications": "Notifications",
  "your_orders": "Your Orders",
  "refresh": "Refresh",
  "retry": "Retry",
  "no_notifications": "No New Notifications",
  "error": "Unknown Error occurred",
  "loading": "Loding...",
  "no_reviews": "No Reviews",
  "be_first_reviewer": "Be first reviewer",
  "phone_number_isn't_available": "Phone number is not availabe",
  "no_orders": "No Orders Available",
  "refresh_data": "Refresh",
  "write_your_product_name": "Write the product name",
  "add_product": "Add Product",
  "distenation": "Distenation",
  "continue": "Continue",
  "unkown": "Unkown",
  "error_happened": "An error happend, try again later",
  "submit_order": "Submit Order",
  "are_you_sure": "Are you sure?",
  "submit_an_order": "submit an order",
  "start_searching_now": "Start searching now",
  "please_choose_the_products": "Please, Enter products first",
  "no_products": "No product entered",
  "signing_out": "Are you sure you want sign out ?",
  "sign_out_b": "Sign Out",
  "order_note": "Order Note",
  "enter_valid_copoun": "Coupon is not correct",
  "you_have_discount": "You have a discount",
  "order_submitted": "Order Submitted",
  "order_submitted_desc1":
      "A notification has been sent to all drivers, And you can follow drivers' offers from the Orders tab",
  "back_to_home_screen": "Back to home screen",
  "filter": "Filter",
  "search_distance": "Search Distance",
  "apply_filter": "Show",
  "products_toBuy": "Orders",
  "delivery_address": "Delivery Address",
  "pick_your_location": "Select your location",
  "satelite": "Satelite",
  "hyprid": "Hybrid",
  "normal": "Normal",
  "same_as_phone_number": "Same phone number you entered previously?",
  "tap_to_name_product": "Tap to enter product name",
  "show": "Show",
  "bet": "Bet",
  "write_your_bet": "Write your delivery offer",
  "enter_delivery_cost": "Delivery Cost",
  "enter_delivery_time": "Delivery Deadline",
  "enter_bet": "Submit your offer",
  "order_betted":
      "Your order was submitted, Wait for the client to review your offer",
  "order_already_betted": "You have already submitted your offer",
  "driver_bets_on_order": "Drivers' Offers",
  "choose_bet": "Choose this offer from ",
  "conferm_driver":
      "When you choose to offer the driver, the driver will contact you and deliver your order at the specified time",
  "choose_this_driver": "Choose Driver Offer",
  "will_deliver_your_order": "I can deliver your offer for",
  "show_offers": "Show Delivery Offers",
  "now_offers_yet": "No Offers yet",
  "order_assigned": "Order has been forwarded to the Driver",
  "choose_driver": "Choose Driver",
  "new_order_message": "New message about",
  "rate_driver": "Rate Driver",
  "chat_with_client": "Contact with client",
  "update_order_status": "Update order Status",
  "rate_client": "Rate Client",
  "enter_total_cost": "Please enter total cost",
  "total_cost": "Total cost",
  "update_order": "Update Order",
  "order_status_update_completed": "Order status has been updated",
  "the_map": "Map",
  "current_orders": "Current Orders",
  "total_products_cost": "Total product cost",
  "no_image_picking_permission":
      "The OS no longer allows you to open your photos, go to settings to give the app the permission.",
  "order_delivery_status": "Delivery Status",
  "connecting": "Delivering",
  "delivery_done": "Delivery Accomplished",
  "choose_status": "Choose Status",
  "no_permission": "No Permission",
  "from_driver": "From",
  "copyed_to_clipboard": "Copied to Clipboard",
  "problem_terms": "Problem Reporting Terms",
  "problem_notes": "Note",
  "write_your_problem": "Write your problem description...",
  "problem_images": "Images",
  "add_problem_images": "Add problem image",
  "see_driver_reviews": "about the driver",
  "you_can_cancel_after": "you can cancel the order within",
  "do_you_want_to_cancel": "Do you want to cancel the order?",
  "you_have_to_reorder":
      "You order cancelation will be final, and can't be reversed",
  "cancel_now": "Cancel Now",
  "order_was_cancelled": "Order cancelled",
  "enter_this_field": "Please, Enter those info",
  "title": "Address",
  "enter_title": "Enter your complaint...",
  "send": "Send",
  "complain_was_successful": "Sent Successfuly",
  "driver_can_not_take_order_again":
      "You can't bet on or take this order again",
  "image": "Attach Image",
  "voice_note": "Attach Voice Note",
  "drivers_reviews": "Drivers Reviews",
  "clients_reviews": "Client Reviews",
  "total_order_delivery_fees": "Order total delivery price",
  "you_have": "You have",
  "in_your_account_balance": "in your balance",
  "upload_bank_validation": "Upload bank validation image",
  "banck_validation_success": "Uploaded Successfuly",
  "upload": "Upload image",
  "pick_another_image": "Pick another one",
  "you_should_upload_validation": "you should upload validation",
  "enter_between": "enter price between",
  "and": "and",
  "after_removing_comission": "after removing comission",
  "change_order_status_first": "change order status first",
  "km": "km",
  "m": "m",
  "you": "you",
  "pick_up_location": "pick up location",
  "delivery_location": "drop location",
  "custom_request": "quick order",
  "choose_loction": "choose location",
  "drop_location": "drop to",
  "choose_drop_location": "choose drop location",
  "pickup_point": "pickup point",
  "choose_pickup_point": "choose pickup point",
  "custom_package_order": "custom package order",
  "location_perrmison_denied": "location perrmison denied",
  "must_enable_from_settings": "must enable from settings",
  "must_open_location_services": "must open location services",
  "phone_number_is_too_long": "phone number is too long",
  "phone_number_is_too_short": "phone number is too short",
  "car_image_is_missing_2": "car image is missing 2",
  "car_image_is_missing": "car image is missing",
  "form_image_is_missing": "form image is missing",
  "license_image_is_missing": "license image is missing",
  "id_image_is_missing": "id image is missing",
  "validaton_faliure": "validaton faliure",
  "too_short": "too short",
  "enter_personal_id": "enter personal id",
  "enter_your_stc_no": "enter your stc no",
  "enter_your_phone_no": "enter your phone no",
  "enter_your_email": "enter your email",
  "name_is_too_short": "name is too short",
  "enter_your_name": "enter your name",
  "back": "back",
  "not_valid_ksa_phone_number": "not valid ksa phone number",
  "phone": "phone",
  "unkwon_error": "unkwon error",
  "must_pick_profile_picture": "must pick profile picture",
  "code_has_been_sent_to_your_phone": "code has been sent to your phone",
  "must_sign_up_first": "must sign up first",
  "app_name": "app name",
};
