include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - packages/**
  errors:
    sort_pub_dependencies: ignore
    deprecated_member_use_from_same_package: ignore
    import_of_legacy_library_into_null_safe: ignore
