name: flutter_chat_bubble
description: Flutter widget for creating different types of chat bubble. You can use different properties of this Widget and create beautiful Chat Bubbles.
version: 1.0.2
homepage: https://github.com/KinjalDhamat312/FlutterChatBubble.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: chat.com.flutter_chat_bubble
    pluginClass: FlutterChatBubblePlugin
